# Generated by Django 4.2.1 on 2023-06-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='lang',
            field=models.CharField(default='ru', max_length=5, verbose_name='Lang'),
        ),
    ]
